### ISSUE TITLE
Linting doesn't work if project not at root

### ISSUE THREAD

**Issue by elldritch** [nwolverson/atom-ide-purescript#103]
I work in a monorepo, so my editor is always opened to the root of the PureScript project. Whenever the linter runs, I get a `Doesn't look like a purescript project - didn't find any src dir` warning and the linting fails.

**Comment by nwolverson** [comment]
What does your project structure look like?

Your editor should be open at either the PureScript project level (where you would run `pulp` etc if building standalone), or at least something below it's src directory. If your PS project doesn't follow the standard convention, it won't be found - that's something I'm looking to change, by looking for the `bower.json` rather than a `src` directory.

**Comment by elldritch** [comment]
My project looks like

```
monorepo/
  project1/
    // ...
  project2/
    src/
      Main.purs
    bower.json
  more-projects/
  // ...
```

I think the ideal way to check for projects is to look upwards from the current PureScript file and check for any `bower.json` or `src` that makes it a valid project (rather than checking from the folder the editor is opened on).

**Comment by nwolverson** [comment]
Hmm. Upcoming changes maybe make this a possibility. The downside of being file based is that commands like "full rebuild" will only work with an active PureScript editor

For now purescript project must be 1:1 with atom "project folder". You can open a 2nd atom window for one of the purescript projects.
