### ISSUE TITLE
psc-ide rebuild isn't being called

### ISSUE THREAD

**Issue by kritzcreek** [nwolverson/atom-ide-purescript#106]
Eventhough the _fast-rebuild_ checkbox in the options is checked.

I'm running the current master.

Another thing I noticed is that you are running a load command with dependencies after each safe. That command will no longer do anything, since support for the `dependencies` option got removed. There is only the full load or module specific load.

**Comment by nwolverson** [comment]
Fast rebuild - this was working for me for sure. Has it actually connected to psc-ide-server?

The load command - largely this is an effect of trying to support multiple versions, since the older versions of psc-ide-server needed to have this load for a particular file. Would be good to sit down and work out a strategy here.

**Comment by kritzcreek** [comment]
For the load command, allright that's totally what I intended with not making it an error. If that's a backwards compatibilty feature I never said anything.
