### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by yazla** [nwolverson/atom-ide-purescript#141]
Hello there,

I am getting this error when building from Atom.

`Error running PureScript build command: Error: Didn't find JSON output at Object.exports.error (C:\Users\Yuriy.atom\packages\ide-purescript\lib\main.js:2925:12) at __do (C:\Users\Yuriy.atom\packages\ide-purescript\lib\main.js:9651:103) at ChildProcess. (C:\Users\Yuriy.atom\packages\ide-purescript\lib\main.js:8478:42) at emitTwo (events.js:106:13) at ChildProcess.emit (events.js:191:7) at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)`

In cmd it builds just fine.

Would appreciate any suggestions.

**Comment by nwolverson** [comment]
Is this running the explicit build command (rather than the "fast rebuild on save")?

What is your configuration of the extension (particularly the build command), psc, pulp version? The default build command used is `pulp build -- --json-errors`, it looks at a glance that there is some command not returning JSON errors as per psc.

**Comment by yazla** [comment]
Thanks for a quick response.

Actually the default was this:
`pulp.cmd --no-psa --json-errors`

And I didn't find the --no-psa option in pulp docs. So now I changed the build line to what you suggested and it started to work just fine.

Thanks a lot!

**Comment by nwolverson** [comment]
Aha, apparently I forgot to publish recent changes. Unfortunately `pulp` changed its argument format in recent versions, so the previous default build command is no longer correct if you have a more recent version.

I've published an updated version, thanks to this.
