### ISSUE TITLE
Show inferred types on collapsed tooltip

### ISSUE THREAD

**Issue by jmatsushita** [nwolverson/atom-ide-purescript#161]
Hi there,

Thanks a lot for the great module!

It would be great to be able to configure whether tooltips are shown folded or not. In particular when using holes, the default tooltip really always needs clicking on the small arrow...

![image](https://user-images.githubusercontent.com/356097/26904665-4ab5f84e-4be3-11e7-9814-4ed5cc573b51.png)

Maybe it's a matter of formatting in this case, since there is room for instance in the panel:

![image](https://user-images.githubusercontent.com/356097/26904660-42ca76fa-4be3-11e7-9768-3ceb46c38690.png)

But for a lot of errors, particularly type errors, usually the clicking on the small arrow will pretty much be always needed to see relevant information.

Cheers,

Jun

**Comment by jmatsushita** [comment]
Ah, I see that it's more of a linter thing. In that case I guess it would help to just move the first line in the unfolded tooltip inside the text of the folded tooltip for inferred types? 

![image](https://user-images.githubusercontent.com/356097/26905044-46312e54-4be5-11e7-9750-3112affd0497.png)

**Comment by nwolverson** [comment]
Types are formatted in the compiler. Not sure I want to start mangling them, ideally there might be a single-line error format in the compiler...

I do worry if you fold the hole type onto one line in this instance, it will be over-long in most cases - need to see how the wrapping is

(The additional lines part of those bubbles are ugly and can surely be improved, but I guess that's a separate issue)

**Comment by nwolverson** [comment]
Tooltips now are completely expanded, due to using different tooltip UI:

![screen shot 2018-01-02 at 22 30 28](https://user-images.githubusercontent.com/2770891/34502718-b5635e2a-f00c-11e7-9ea8-caff99c3b8da.png)

Funnily enough with the "full description" toggle off the diagnostics panel also removes newlines, working well in this case:
![screen shot 2018-01-02 at 22 32 37](https://user-images.githubusercontent.com/2770891/34502748-dd5528fa-f00c-11e7-86a5-348c168ad28e.png)
