### ISSUE TITLE
Incorrect Module not found error 

### ISSUE THREAD

**Issue by halcwb** [nwolverson/atom-ide-purescript#167]
On some module imports I get a module not found error. This applies to installed modules as to source modules. The project builds fine, so the modules are imported. This happens with some imports but not all.

<img width="1440" alt="atompurs" src="https://user-images.githubusercontent.com/683631/28198013-317538a6-685b-11e7-8163-132e2535130b.png">

**Comment by nwolverson** [comment]
Can you try cleaning your `output/` directory and running a full build? Could be you have some incorrectly versioned externs

**Comment by halcwb** [comment]
You're correct, thanks.

**Comment by safareli** [comment]
This happens too often with me.

**Comment by nwolverson** [comment]
@safareli do you have an example scenario? Out of date externs should not happen very often unless you are switching compiler versions strangely often. 

I think any resolution of this will involve compiler/psc-ide changes, but I'd hesitate to recommend opening an issue without some better information

**Comment by safareli** [comment]
No I have not :/
I have ps globally plus ps in node_modules of a project, so maybe there is some conflict.
Removing output and rebuilding, restarting ide or atom couple times fixes it.

**Comment by nwolverson** [comment]
If you have npm local purescript it will be picked up from npm script but
not otherwise, so eg avoid doing pulp build when you normally build via
script. Make sure ide plugin has "use npm bin" set if you want to use that
one. If you do use inconsistent versions and the fix with rebuilding, the
"restart ide server" command in the plugin should sort you out without
restarting editor.

In the future we can probably detect this bad situation and at least prompt
a rebuild.

**Comment by safareli** [comment]
Did not noticed `use npm bin`, will use that thanks.

> In the future we can probably detect this bad situation and at least prompt a rebuild.

Good idea!
