### ISSUE TITLE
undo can break after auto importing modules

### ISSUE THREAD

**Issue by stratospark** [nwolverson/atom-ide-purescript#69]
Using ide-purescript v0.11.0, with purescript v0.8.4.0

If you are typing in the middle of a line, then import a module through autocompletion, it can break the undo.

Here is a simple reproduction:

```
module Sample where

main = pri`
```

autocomplete print and add a string

```
module Sample where

import Control.Monad.Eff.Console (print)

main = print "hello world! this is a very long string!"
```

Try and insert "$ toUpper", autocompleting the import

```
module Sample where

import Control.Monad.Eff.Console (print)
import Data.String (toUpper)

main = print $ toUpper "hello world! this is a very long string!"
```

Now undo twice:

```
module Sample where

import Control.Monad.Eff.Console (print)

main = print $ toUppd! this is a very long string!"
```

**Comment by nwolverson** [comment]
Wow ok, this is probably a result of the super hacky way in which this works due to autocomplete+ limitation (no duplicate completions). I'm inserting the fully-qualified identifier then doing an edit to remove the qualified part, _bypassing undo_ so that you don't see that intermediate state when you undo.

Maybe not bypassing undo would help but then you see the fully-qualified version when you undo first..

**Comment by nwolverson** [comment]
Even worse with redo. Back to the drawing board...

**Comment by nwolverson** [comment]
This should now be fixed as I found a different workaround, undo/redo now seems to work and I can delete code.

Thanks!
