### ISSUE TITLE
Can't type inside the Psci console

### ISSUE THREAD

**Issue by RAbraham** [nwolverson/atom-ide-purescript#70]
Hi,
I can't type inside the Psci tab opened within atom. But I can successfully execute `send selection` and see results.  

I'm on 0.11, OS X

**Comment by nwolverson** [comment]
There is currently no functionality to type within the psci tab. This was originally put together along the lines of ionide's fsi tab, but send-selection is a more useful workflow for F# than here. 

I'm thinking to add a separate line-entry panel at the bottom of the psci tab - though potentially we'd prefer a multiline area for multiline mode? Either way probably better to have a separate text-entry box rather than trying to do edit in-place, which might be a bit funky

**Comment by RAbraham** [comment]
Cool, good to know that it's as designed. I just thought that people may expect(not necessarily want) the same behaviour as running `pulp psci` on the command line, as they both look similar and are named the same.
Multiline support sounds awesome. I look forward to it. Thanks for creating this plugin!
