### ISSUE TITLE
Autocompletion always uses fully qualified names

### ISSUE THREAD

**Issue by rtpg** [nwolverson/atom-ide-purescript#84]
- I have a module `App.Models`, in which I declare `lookupUser`.
- In `App.Views`, I try to use autocompletion to import `lookupUser`  by typing `lookup` and triggering autocomplete.
- this ends up autocompleting to `App.Models.lookupUser`, with `import App.Models (lookupUser)` added to the top. Pretty sure the autocomplete should just make `lookupUser`.
  
  I'm using Purescript 0.8.6, with `atom-ide-purescript` 0.13.5.

**Comment by nwolverson** [comment]
Related to a hack to workaround https://github.com/atom/autocomplete-plus/issues/615 - the completion will insert the fully qualified name if snippets are not enabled.

I guess I could further restrict the hack to only apply when snippets are enabled - but otherwise there would be no support for completing functions which appear in multiple modules correctly.

**Comment by nwolverson** [comment]
I believe this is no longer the case, the linked issues is resolved and the above hack is not performed.
