### ISSUE TITLE
pursuit search problems: (function search hang, module search slow start, in both cases, no loading message, only a non descriptive hourglass)

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#93]
pursuit search seems to have a few problems: 
- function search seems to keep loading until I press write something
  ![image](https://cloud.githubusercontent.com/assets/2150990/16731482/a25df648-4778-11e6-8517-31cc8eac69f0.png)
  if I press <enter> with no text given, it closes.
- [ ] how about it remaining open if no escape key pressed ?
- [ ] how about removing the ⌛ symbol once it's ready to search ? (maybe add a small help text ?)
- module search starts slowly (~5 seconds) and never find anything (no matches found)
- [ ] how about a message explaining what it's doing during the load time ? this way, I could diagnose why it doesn't find anything ?

**Comment by nwolverson** [comment]
Need to look at this once regular pursuit search is working normally again.

**Comment by nwolverson** [comment]
Currently Pursuit search is up but the JSON format is no longer understood by psc-ide, and doesn't contain all we need. This may be a while.

**Comment by nwolverson** [comment]
The inability to search has been resolved for quite some time, but I just tweaked the UI to remove hourglass & give filter prompt, search instead of dismiss on enter. Toyed with adding "loading" indication while searching but due to the positioning at the top of `SelectListView` this bounces around the list in a way which I find more irritating than no feedback.
