### ISSUE TITLE
[keybindings suggestion] no 'cmd-enter' overwriting + default 2-keys combo for most features + settings doc

### ISSUE THREAD

**Issue by rvion** [nwolverson/atom-ide-purescript#99]
here are a few suggestions regarding keybindings:
### 1. Better settings page:

How about doing something in settings for keybindings discoverability, like [this package](https://github.com/MichaelAquilina/python-tools) (many other packages do that too)

![image](https://cloud.githubusercontent.com/assets/2150990/16802441/e00a0d72-4900-11e6-98bf-95e91bb64833.png)
- self discoverability in settings,
- documentation about ability to change them easilly
- quick way of disabling them if needed.

it would also further help people discovering the plugin features
### 2. no `<cmd>-<enter>` overwriting :

since `sublime text`, `atom`, and some other web-based editor preset use `<cmd>-<enter>` to insert a newline after the current line and place the cursor on it, _I think_ that many people will not be very happy with this default keybinding. 
### 3. default 2keys shortcuts for regular functions

for all of those functions:
![image](https://cloud.githubusercontent.com/assets/2150990/16802610/e255a09a-4901-11e6-993d-ebdcd35de18f.png)

there could be some default keybindings like
- `<cmd>-K <cmd>-B`
- `<cmd>-K <cmd>-S`
- `<cmd>-K <cmd>-T`
- `<cmd>-K <cmd>-A`
- ...

(or something else if `<cmd>-K` is already in use in some other popular package

I think it would help both to
- speedup power usage onboarding 
- provide a no-configuration experience

**Comment by nwolverson** [comment]
Keybindings in settings is a good idea. I'm not sure how that is done, as looking at packages that have it I don't see anything relating to that.

Cmd-enter: Not sure if I took this directly or was meant to be instead of alt-enter - I think this is used to send text to interactive buffers elsewhere.

Default keybindings: Was going to consider using same keybindings as idris does for something like add clause/case split. I'm not really using much in the way of keybindings so be interested if someone has some already.

**Comment by nwolverson** [comment]
Apparently I just need to fix the namespace in commands to be `ide-purescript:` for them to be included in settings keymap.

**Comment by rvion** [comment]
cool :)

btw, instead of 

> ```
> <cmd>-K <cmd>-B
> <cmd>-K <cmd>-S
> <cmd>-K <cmd>-T
> <cmd>-K <cmd>-A
> ```

I went for something like 

ctrl-o i

```
ctrl-o b
ctrl-o s
ctrl-o t
ctrl-o a
...
```

to avoid conflicts

``` yaml
'atom-workspace atom-text-editor:not([mini])':
    'alt-enter':'purescript:show-quick-fixes'
    'ctrl-o i':'purescript:add-explicit-import'
    # ...
```

**Comment by jlavelle** [comment]
Binding the commands to ctrl-o ... doesn't play nicely with a default Atom setup as it's the open-file hotkey, is there even a way to use these shortcuts as they are without rebinding open-file?

**Comment by nwolverson** [comment]
OH dear, I didn't notice as I'm on Mac.

We can either choose a different shortcut or make it platform specific if required - ideas?

For right now, you can disable the shortcuts in settings view, and there's a copy/clipboard icon which will copy the keybinding to put in your personal keybindings file

**Comment by jlavelle** [comment]
I ended up doing [this](https://github.com/jlavelle/atom-ide-purescript/blob/master/keymaps/core.cson#L23-L34).     Since I don't have a Mac to test this with or know very much about Atom I just left the old bindings in place without adding more specificity to them, it doesn't seem to interfere with anything on Windows since the Open File binding overrides it.

**Comment by nwolverson** [comment]
can use `.platform-darwin` for mac-specific bindings. But we could also just use `^i` on both?

I don't really have any strong feelings about keybindings, in my ideal world someone would have a strong preference or justification and I can just merge some bindings....

Only qualitative things:
- the 2-part binding is nice because it only takes up 1 key combination for the prefix and doesn't require weird multi modifier contortions
- it's a shame the prefix doesn't suggest PureScript

**Comment by jlavelle** [comment]
I also think the 2-part binding is nice and I wish that pattern was more common, adding extra modifiers breaks flow.  

Using `^i` has been working out well for me and I'm not aware of it being bound elsewhere on any platform, so it could be an option if you want to merge the bindings for simplicity.  Maybe it even stands for ide-purescript :)
